<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LRFbDRD' shared service.

return $this->privates['.service_locator.LRFbDRD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminFeedbackController::index' => ['privates', '.service_locator.n8gOTNr', 'get_ServiceLocator_N8gOTNrService.php', true],
    'App\\Controller\\AdminProductsController::admin' => ['privates', '.service_locator.n8gOTNr', 'get_ServiceLocator_N8gOTNrService.php', true],
    'App\\Controller\\ContactsController::index' => ['privates', '.service_locator.8ZuNAXa', 'get_ServiceLocator_8ZuNAXaService.php', true],
    'App\\Controller\\DefaultController::index1' => ['privates', '.service_locator.8ZuNAXa', 'get_ServiceLocator_8ZuNAXaService.php', true],
    'App\\Controller\\GenderProductController::pagination' => ['privates', '.service_locator.n8gOTNr', 'get_ServiceLocator_N8gOTNrService.php', true],
    'App\\Controller\\ProductController::products' => ['privates', '.service_locator.n8gOTNr', 'get_ServiceLocator_N8gOTNrService.php', true],
    'App\\Controller\\ProductTypeController::index' => ['privates', '.service_locator.n8gOTNr', 'get_ServiceLocator_N8gOTNrService.php', true],
    'App\\Controller\\AdminFeedbackController:index' => ['privates', '.service_locator.n8gOTNr', 'get_ServiceLocator_N8gOTNrService.php', true],
    'App\\Controller\\AdminProductsController:admin' => ['privates', '.service_locator.n8gOTNr', 'get_ServiceLocator_N8gOTNrService.php', true],
    'App\\Controller\\ContactsController:index' => ['privates', '.service_locator.8ZuNAXa', 'get_ServiceLocator_8ZuNAXaService.php', true],
    'App\\Controller\\DefaultController:index1' => ['privates', '.service_locator.8ZuNAXa', 'get_ServiceLocator_8ZuNAXaService.php', true],
    'App\\Controller\\GenderProductController:pagination' => ['privates', '.service_locator.n8gOTNr', 'get_ServiceLocator_N8gOTNrService.php', true],
    'App\\Controller\\ProductController:products' => ['privates', '.service_locator.n8gOTNr', 'get_ServiceLocator_N8gOTNrService.php', true],
    'App\\Controller\\ProductTypeController:index' => ['privates', '.service_locator.n8gOTNr', 'get_ServiceLocator_N8gOTNrService.php', true],
], [
    'App\\Controller\\AdminFeedbackController::index' => '?',
    'App\\Controller\\AdminProductsController::admin' => '?',
    'App\\Controller\\ContactsController::index' => '?',
    'App\\Controller\\DefaultController::index1' => '?',
    'App\\Controller\\GenderProductController::pagination' => '?',
    'App\\Controller\\ProductController::products' => '?',
    'App\\Controller\\ProductTypeController::index' => '?',
    'App\\Controller\\AdminFeedbackController:index' => '?',
    'App\\Controller\\AdminProductsController:admin' => '?',
    'App\\Controller\\ContactsController:index' => '?',
    'App\\Controller\\DefaultController:index1' => '?',
    'App\\Controller\\GenderProductController:pagination' => '?',
    'App\\Controller\\ProductController:products' => '?',
    'App\\Controller\\ProductTypeController:index' => '?',
]);
