<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ2eOxF2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ2eOxF2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ2eOxF2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ2eOxF2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJ2eOxF2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'J2eOxF2',
    'container.build_id' => '15144064',
    'container.build_time' => 1587311715,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ2eOxF2');
